config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :aankoopfacturens
  resources :invoices
  root "nl#home"
  get 'watdoenwe' => 'nl/diensten'
  get 'nl/digitalconsulting'
  get 'nl/sectoren'
  get 'nl/overons'
  get 'static/home'
  get 'static/legal'
  get 'static/privacy'
  get 'static/terms'
  get 'nl/hrconsulting'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aankoopfacturen.rb
class Aankoopfacturen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/controllers/aankoopfacturens_controller.rb
class AankoopfacturensController < ApplicationController
  before_action :set_aankoopfacturen, only: %i[ show edit update destroy ]

  # GET /aankoopfacturens or /aankoopfacturens.json
  def index
    @aankoopfacturens = Aankoopfacturen.all
  end

  # GET /aankoopfacturens/1 or /aankoopfacturens/1.json
  def show
  end

  # GET /aankoopfacturens/new
  def new
    @aankoopfacturen = Aankoopfacturen.new
  end

  # GET /aankoopfacturens/1/edit
  def edit
  end

  # POST /aankoopfacturens or /aankoopfacturens.json
  def create
    @aankoopfacturen = Aankoopfacturen.new(aankoopfacturen_params)

    respond_to do |format|
      if @aankoopfacturen.save
        format.html { redirect_to aankoopfacturen_url(@aankoopfacturen), notice: "Aankoopfacturen was successfully created." }
        format.json { render :show, status: :created, location: @aankoopfacturen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aankoopfacturen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aankoopfacturens/1 or /aankoopfacturens/1.json
  def update
    respond_to do |format|
      if @aankoopfacturen.update(aankoopfacturen_params)
        format.html { redirect_to aankoopfacturen_url(@aankoopfacturen), notice: "Aankoopfacturen was successfully updated." }
        format.json { render :show, status: :ok, location: @aankoopfacturen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aankoopfacturen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aankoopfacturens/1 or /aankoopfacturens/1.json
  def destroy
    @aankoopfacturen.destroy

    respond_to do |format|
      format.html { redirect_to aankoopfacturens_url, notice: "Aankoopfacturen was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aankoopfacturen
      @aankoopfacturen = Aankoopfacturen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aankoopfacturen_params
      params.require(:aankoopfacturen).permit(:bedrijfsnaam, :adres, :land, :postcode, :btw, :klantnummer, :factuurnummer, :description, :excl_bedrag, :factuurdatum, :vervaldatum, :rekeningnummer, :begunstigde, :mededeling, :factuur_mail, :betaald, :bevestigd, :recurrent, :opmerking, :staving)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:bedrijfsnaam, :contactnaam, :email, :tel, :onderwerp)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:fnummer, :datum, :bedrijfsnaam, :adres1, :adres2, :postcode, :stad, :email, :btw, :beschrijving, :bedragexcl, :btw, :bedragincl, :opmerkingen, :barcode)
    end
end

app/controllers/nl_controller.rb
class NlController < ApplicationController
  def home
  end

  def diensten
  end
  
  def digitalconsulting
  end
  
  def hrconsulting
  end

  def sectoren
  end

  def overons
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def legal
  end

  def privacy
  end

  def terms
  end
end

app/helpers/aankoopfacturens_helper.rb
module AankoopfacturensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/nl_helper.rb
module NlHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/aankoopfacturens/_aankoopfacturen.html.erb
<div id="<%= dom_id aankoopfacturen %>">
  
  <tbody class="divide-y divide-gray-200 bg-white">
    <tr>
      <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= aankoopfacturen.bedrijfsnaam %></td>
      <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= ((aankoopfacturen.excl_bedrag)*1.21).truncate(2) %></td>
      <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= aankoopfacturen.vervaldatum %></td>
      <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= aankoopfacturen.betaald %></td>
      <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= aankoopfacturen.bevestigd %></td>
      <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
        <%= link_to "Bekijken", aankoopfacturen, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-base" %>
        <%= link_to 'Aanpassen', edit_aankoopfacturen_path(aankoopfacturen), class: "py-3 ml-2 px-5 inline-block font-base" %>
      </td>
    </tr>
  </tbody>

  
</div>

app/views/aankoopfacturens/edit.html.erb
<div class="mx-auto md:w-2/3 w-full my-7">
  <h1 class="font-bold text-4xl">Aankoopfactuur <%= @aankoopfacturen.id%> van <%= @aankoopfacturen.bedrijfsnaam%></h1>

  <%= render "form", aankoopfacturen: @aankoopfacturen %>

  <%= link_to "Show this aankoopfacturen", @aankoopfacturen, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to aankoopfacturens", aankoopfacturens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/aankoopfacturens/index.html.erb
<div class="container mx-auto py-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
</div>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-4xl font-semibold text-gray-900">Aankoopfacturen</h1>
      <p class="mt-2 text-sm text-gray-700">Alle binnenkomende facturen.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
    <%= link_to 'Nieuw aankoopfacturen', new_aankoopfacturen_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  </div>
  <div id="aankoopfacturens" class="min-w-full">
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
  </div>
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Bedrijfsnaam</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Bedrag (EUR)</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Vervaldatum</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Betaald</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Bevestigd</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="text-indigo-600 hover:text-indigo-900"></span>
                </th>
              </tr>
            </thead>
                    <%= render @aankoopfacturens %>
      </table>
    
  </div>
  
        <div class="sm:flex-auto mt-7">
      <h1 class="text-4xl font-semibold text-gray-900">Terug te vorderen btw: <%= (@aankoopfacturens.sum(:excl_bedrag))*0.21 %> EUR</h1>
      <p class="mt-2 text-sm text-gray-700"></p>
    </div>
    
    
</div>

app/views/aankoopfacturens/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New aankoopfacturen</h1>

  <%= render "form", aankoopfacturen: @aankoopfacturen %>

  <%= link_to 'Back to aankoopfacturens', aankoopfacturens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/aankoopfacturens/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @aankoopfacturen %>

    <%= link_to 'Edit this aankoopfacturen', edit_aankoopfacturen_path(@aankoopfacturen), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this aankoopfacturen', aankoopfacturen_path(@aankoopfacturen), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to aankoopfacturens', aankoopfacturens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Bedrijfsnaam:</strong>
    <%= contact.bedrijfsnaam %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Contactnaam:</strong>
    <%= contact.contactnaam %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= contact.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Tel:</strong>
    <%= contact.tel %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Onderwerp:</strong>
    <%= contact.onderwerp %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this contact", contact, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this contact', edit_contact_path(contact), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, class: "contents") do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-5 font-raleway">
    Goedemiddag consultant van Eliama & Otileo,
        <br>
            <br>
    Mijn naam is <%= form.text_field :contactnaam, class: "underline-offset-8 px-3 py-1 m-2 border-yellow-500" %> van het bedrijf <%= form.text_field :bedrijfsnaam, class: "border-yellow-500 px-3 py-1 m-2" %>
    <br>
        <br>
    Graag had ik met jullie besproken of jullie het volgende kunnen doen voor ons:
    <br>
        <br>
    <%= form.text_area :onderwerp, rows: 4, class: "block shadow rounded-md border border-yellow-500 outline-none px-3 py-2 mt-2 w-full" %>
    <br>
    <br>
    U mag me contacteren via mijn e-mail <%= form.text_field :email, class: "border-yellow-500 px-3 py-1 m-2" %> <br>of telefonisch op het nummer <%= form.text_field :tel, class: "border-yellow-500 px-3 py-1 m-2" %>
    <br>
    <br>
    Alvast bedankt en tot snel.

  </div>

  <div class="inline m-5">
    <%= form.submit "Verzenden", class: "font-raleway rounded-lg py-3 px-5 bg-yellow-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing contact</h1>

  <%= render "form", contact: @contact %>

  <%= link_to "Show this contact", @contact, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

</div>

app/views/contacts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Contacts</h1>
    <%= link_to 'New contact', new_contact_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="contacts" class="w-full">
    <%= render @contacts %>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @contact %>

  </div>
</div>

app/views/invoices/_invoice.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-white mt-5 shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-7 sm:px-6">
    <img class="h-10 w-auto sm:h-12" src="https://res.cloudinary.com/the-ruby-lab/image/upload/v1652309224/3_w436ke.png" alt="">
    <h3 class="text-2xl font-raleway text-gray-900">FACTUUR <%= invoice.fnummer %></h3>
    <p class="mt-3 max-w-2xl text-sm text-gray-500"><%= invoice.datum %></p>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">Factuurdatum: 25/05/2022</p>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">Vervaldatum: 26/05/2022</p>
    <p class="mt-1 max-w-2xl text-sm text-gray-500 font-libre">Code: <%= invoice.barcode %></p>
  </div>
  <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
    <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
      <div class="sm:col-span-1 font-raleway">
        <dt class="text-md text-yellow-600 font-bold">Eliama & Otileo BV</dt>
        <dd class="mt-1 text-sm text-gray-900">BE 0785.992.879</dd>
        <dd class="mt-1 text-sm text-gray-900">Zavelstraat 84</dd>
        <dd class="mt-1 text-sm text-gray-900">3010, Leuven</dd>
      </div>
      <div class="sm:col-span-1 font-raleway">
        <dt class="text-md text-yellow-600 font-bold"><%= invoice.bedrijfsnaam %></dt>
        <dd class="mt-1 text-sm text-gray-900">BE 0845.093.395</dd>
        <dd class="mt-1 text-sm text-gray-900"><%= invoice.adres1 %></dd>
        <dd class="mt-1 text-sm text-gray-900"><%= invoice.postcode %>, <%= invoice.stad %></dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Email address</dt>
        <dd class="mt-1 text-sm text-gray-900">finance@eliamaotileo.com</dd>
      </div>
      <div class="sm:col-span-1">
        <dt class="text-sm font-medium text-gray-500">Email boekhouding</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= invoice.email %></dd>
      </div>
      <div class="sm:col-span-2">
        <dt class="text-sm font-medium text-gray-500">Beschrijving</dt>
        <dd class="mt-1 text-sm text-gray-900"><%= invoice.beschrijving %></dd>
      </div>
      <div class="sm:col-span-2">
        <dt class="text-sm font-medium text-gray-500">Bedragen</dt>
        <dd class="mt-1 text-sm text-gray-900">
          <ul role="list" class="border border-gray-200 rounded-md divide-y divide-gray-200">
            <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
              <div class="w-0 flex-1 flex items-center">
                <span class="ml-2 flex-1 w-0 truncate"> Subtotaal: <%= invoice.bedragexcl %> EUR</span>
              </div>
            </li>
            <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
              <div class="w-0 flex-1 flex items-center">
                <span class="ml-2 flex-1 w-0 truncate"> 21% BTW: <%= invoice.btw %> EUR</span>
              </div>
            </li>
            <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm bg-black">
              <div class="w-0 flex-1 flex items-center">
                <span class="ml-2 flex-1 w-0 truncate font-bold text-white"> Totaal: <%= invoice.bedragincl %> EUR</span>
              </div>
            </li>
          </ul>
        </dd>
      </div>
            <div class="sm:col-span-2">
        <dt class="text-sm font-medium text-gray-500">Opmerkingen</dt>
        <dd class="mt-1 text-sm text-gray-900"> <%= invoice.opmerkingen %></dd>
      </div>
    </dl>
  </div>
</div>
  
  <!-- This example requires Tailwind CSS v2.0+ -->
<div class="bg-red-50 shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900">Betaaldetails van begunstigde Eliama & Otileo BV</h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">Factuur te betalen voor <strong>26/05/2022</strong></p>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-red-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Rekeningnummer bij KBC</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">BE38 7340 6011 7272<br>KREDBEBB</dd>
      </div>
      <div class="bg-red-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Te betalen bedrag</dt>
        <dd class="mt-1 text-sm text-gray-900 font-bold sm:mt-0 sm:col-span-2"><%= invoice.bedragincl %> EUR</dd>
      </div>
      <div class="bg-red-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">In mededeling zetten</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= invoice.barcode %></dd>
      </div>
    </dl>
  </div>
</div>

  
  
  <div>

  <% if action_name != "show" %>
    <%= link_to "Show this invoice", invoice, class: "rounded-lg  inline-block font-medium" %>
    <%= link_to 'Edit this invoice', edit_invoice_path(invoice), class: "rounded-lg py-3 ml-2 px-5 inline-block font-medium" %>
    <%= link_to 'Betaling boeken', edit_invoice_path(invoice), class: "rounded-lg py-3 ml-2 px-5 inline-block font-medium text-green-500" %>
    <%= link_to 'Crediteren', edit_invoice_path(invoice), class: "rounded-lg py-3 ml-2 px-5 inline-block font-medium text-red-500" %>
    <%= link_to 'Herinneren', edit_invoice_path(invoice), class: "rounded-lg py-3 ml-2 px-5 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/invoices/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing invoice</h1>

  <%= render "form", invoice: @invoice %>

  <%= link_to "Show this invoice", @invoice, class: "ml-2 rounded-lg p-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to invoices", invoices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/invoices/index.html.erb
<div class="container p-10">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Invoices</h1>
    <%= link_to 'New invoice', new_invoice_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="invoices" class="min-w-full">
    <%= render @invoices %>
  </div>
</div>

app/views/invoices/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New invoice</h1>

  <%= render "form", invoice: @invoice %>

  <%= link_to 'Back to invoices', invoices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/invoices/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @invoice %>

    <%= link_to 'Edit this invoice', edit_invoice_path(@invoice), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this invoice', invoice_path(@invoice), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to invoices', invoices_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>